### ISSUE TITLE
crash when generating the world

### ISSUE THREAD

**Issue by DasIstVoltone** [Hennamann/Wasteland#13]
[crash-2018-06-08_22.54.54-server.txt](https://github.com/Hennamann/Wasteland/files/2084422/crash-2018-06-08_22.54.54-server.txt)

**Comment by el1xlv** [comment]
same problem

**Comment by el1xlv** [comment]
Try download mod from developer site: https://maven.henrikstabell.com/com/legacy/wastelands/Wastelands-1.12/1.2.2-11/ (Wastelands-1.12-1.2.2-11-universal.jar)
At least helped for me.

**Comment by Drakoflame** [comment]
> 
> 
> Try download mod from developer site: https://maven.henrikstabell.com/com/legacy/wastelands/Wastelands-1.12/1.2.2-11/ (Wastelands-1.12-1.2.2-11-universal.jar)
> At least helped for me.

El1xlv please... please please please can you link me that file... the maven is down and I really want to use this mod, Hennamen is gone, hasn't been online since June, and it's kinda agrivating.... 115Kino probably won't do anything about the mod, and at this point the mod is as good as dead for a 7th time

**Comment by Hennamann** [comment]
The new version has been released to Curseforge, truly sorry about the delay!
