### ISSUE TITLE
Roguelike Dungeons Not Generating Correctly

### ISSUE THREAD

**Issue by NormanNormalington** [Hennamann/Wasteland#2]
Any Roguelike Dungeons I find in Wasteland biomes spawn with no mob spawners or chests, and every single level of them is the same, made mostly out of just stone bricks and polished andesite. In any other biome the dungeons still generate correctly, with all their various features, decorations and rooms. 

Using Wasteland Reborn 1.0.0, Roguelike Dungeons 1.8.0 and Latest Forge (14.23.1.2583) on MC 1.12.2.

**Comment by Hennamann** [comment]
Hmmm, the wasteland mod is not supposed to be used as a biome mod. In fact, the biomes are not supposed to spawn outside of the wasteland worldtype added by the mod, but due to MC/Forge changes there seems to be no way to circumvent Minecraft from using the biomes in worldgen... 

Besides the issue seems hard to fix as it sounds like an issue on Roguelike Dungeons part and not mine. 

I'll investigate this and then potentially close it. I will add the "wontfix" label to it for the time being though.

**Comment by Hennamann** [comment]
I will be pushing a new release of the mod soon that prevents the Wasteland biomes to spawn in normal world types by default using the config. Which makes this issue irrelevant and I am closing it. If you have any questions or interventions to this decision feel free to comment below.
