### ISSUE TITLE
1.12 Version not working in 1.12.1

### ISSUE THREAD

**Issue by Koltanas** [Hennamann/Wasteland#3]
I noticed that the 1.12 Versions of this mods require 1.12.2,  while here https://minecraft.curseforge.com/projects/wasteland-reborn/files/2517071 it states that it should work for 1.12.1 too.

**Comment by Hennamann** [comment]
Not sure what's going on with that, seems like my upload scripts have set it to support all versions with 1.12 in the name when the mod is in reality only supported in 1.12.2 due to Forge... I'll have that fixed over on Curse right away and see if I can't tweak my upload scripts to avoid this in the future!

**Comment by Hennamann** [comment]
On a separate note, did you need it for 1.12.1? I could compile a build for 1.12.1 for you to use if that's the case.

**Comment by Koltanas** [comment]
No, thanks I just wanted to try it, since I was searching for a new wastelandmod for some tim, but I would have to start a new world for it.
